name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: Archive aar
      uses: actions/upload-artifact@v2
      with:
        name: draftsman
        path: draftsman/build/outputs/aar/**.aar  
      
    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/**/**.apk
